### PR TITLE
Let me request to pull Koeda chan

### PR DESCRIPTION
**Pull request by sol-gel**
"Koeda chan" is the first branch created by T. Ikeya

### CODE REVIEW

**Comment by sol-gel** [comment]
@s-tanoue -san: please approve my pull request.

**Review by s-tanoue — APPROVED** [review]
Thank you!  LGTM!

**Comment by yoshihide-hasegawa** [comment]
Thank you! LGTM!

**Review by s-tanoue — APPROVED** [review]
LGTM!

**Pull request merged**
